apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 2
  selector:
    matchlabels:
      myapp: wordpress
  template:
    metadata:
      labels:
        myapp: wordpress
    spec:
      containers:
        - name: wordpress
          image: klchandrika/wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretkeyRef:
                  name: mysql-secret
                  key: DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretkeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretkeyRef:
                  name: mysql-secret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector: 
    myapp: wordpress
    
                  
